
image:
  file: .gitpod.Dockerfile

ports:
  # Odoo server
  - port: 8069
    onOpen: ignore
  # PostgreSQL server
  - port: 5432
    onOpen: ignore

tasks:
  - init: pip install pylint flake8 phonenumbers pandas num2words psycopg2-binary watchdog xlwt xlrd paramiko pylint-odoo simplejson httpagentparser autopep8 && odoo --stop-after-init
    command: odoo --dev=all

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
